version: '3'

services:

    apollo-configservice:
        image: apolloconfig/apollo-configservice:1.7.0
        container_name: apollo-configservice
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://configdb:3306/ApolloConfigDB?characterEncoding=utf8
            SPRING_DATASOURCE_USERNAME: root 
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            EUREKA_INSTANCE_HOME_PAGE_URL: http://${THIS_SERVER_IP}:8180
        volumes:
            - /tmp/apollo-logs/config:/opt/logs
        ports:
            - 8180:8080
        depends_on:
            - apollo-configdb
        networks:
            - apollo

    apollo-adminservice:
            image: apolloconfig/apollo-adminservice:1.7.0
            container_name: apollo-adminservice
            restart: always
            environment:
                SPRING_DATASOURCE_URL: jdbc:mysql://configdb:3306/ApolloConfigDB?characterEncoding=utf8
                SPRING_DATASOURCE_USERNAME: root 
                SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                EUREKA_INSTANCE_HOME_PAGE_URL: http://${THIS_SERVER_IP}:8190
            volumes:
                - /tmp/apollo-logs/admin:/opt/logs
            ports:
                - 8190:8090
            depends_on:
                - apollo-configdb
                - apollo-configservice
            networks:
                - apollo

    apollo-configdb:
        container_name: apollo-configdb
        build:
            context: mysql
        command: [
            '--default-authentication-plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ../configdb/data:/var/lib/mysql:z
        security_opt:
            - seccomp:unconfined
        ports:
            - 13306:3306
        networks:
            apollo:
                aliases:
                    - configdb


networks:
    apollo:
        driver: bridge